# Default values for aws-efs-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: amazon/aws-efs-csi-driver
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

sidecars:
  livenessProbeImage:
    repository: quay.io/k8scsi/livenessprobe
    tag: "v2.0.0"
  nodeDriverRegistrarImage:
    repository: quay.io/k8scsi/csi-node-driver-registrar
    tag: "v1.3.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podResources:
  efsPlugin: {}
  csDriverRegistrar: {}
  livenessProbe: {}

nodeSelector: {}

tolerations: []

affinity: {}

node:
  podAnnotations: {}
  tolerations: []
